In [1]:
import numpy as np
import array

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array([[1,2,3,45,4],[43,6,57,8,7]])

array([[ 1,  2,  3, 45,  4],
       [43,  6, 57,  8,  7]])

In [6]:
np.array([[1,2,3,45,4],[43,6,57,8,7],[2,45,67]])

array([list([1, 2, 3, 45, 4]), list([43, 6, 57, 8, 7]), list([2, 45, 67])],
      dtype=object)

In [7]:
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [9]:
a=np.array([[[1,2,3],[4,5,6],[6,7,8]]])

In [10]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]]])

In [14]:
a.ndim

3

In [20]:
arr=np.array([(1,2),(3,4)],dtype=[("a","<i2"),("b","<i4")])

In [21]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i4')])

In [26]:
type(arr[0])

numpy.void

In [28]:
type(arr[0][0])

numpy.int16

In [24]:
type(arr)

numpy.ndarray

In [29]:
l=[1,2,3,4,5]


In [30]:
np.array(l)

array([1, 2, 3, 4, 5])

In [31]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [32]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [34]:
a=np.mat(l)

In [35]:
np.asanyarray(a)

matrix([[1, 2, 3, 4, 5]])

In [39]:
issubclass(np.matrix,np.ndarray)

True

In [44]:
a=np.array([[1,2],[3,4]])

In [45]:
a

array([[1, 2],
       [3, 4]])

In [46]:
b=np.copy(a)

In [47]:
a[1][1]=143

In [48]:
a

array([[  1,   2],
       [  3, 143]])

In [49]:
b

array([[1, 2],
       [3, 4]])

In [51]:
b[0:10]

array([[1, 2],
       [3, 4]])

In [52]:
b[-1]

array([3, 4])

In [54]:
for i in b:
    print(i)

[1 2]
[3 4]


In [55]:
#creating numpy array using from function
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [56]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [57]:
gen=(i*i for i in range(5))

In [59]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [61]:

np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [65]:
np.fromstring("21 45 65 43",sep=" ",dtype=int)

array([21, 45, 65, 43])

In [66]:
np.fromstring("21 45 65 43",sep=" ",dtype=complex)

array([21.+0.j, 45.+0.j, 65.+0.j, 43.+0.j])

In [80]:
a=np.array([[[1,2,3,4],[3,4,5,6]],[[1,2,3,4],[3,4,5,6]]])

In [81]:
a

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[1, 2, 3, 4],
        [3, 4, 5, 6]]])

In [82]:
a.shape

(2, 2, 4)

In [79]:
a.size

16

In [89]:
np.arange(2,19)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [88]:
np.arange(12.9,1.5,-2)

array([12.9, 10.9,  8.9,  6.9,  4.9,  2.9])

In [91]:
np.linspace(2,10,8)

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [95]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
np.empty((5,4))

array([[1.43546450e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.30276956e+180, 1.02941932e-071,
        6.97936820e-076],
       [5.06557764e-086, 3.35810380e-143, 6.01433264e+175,
        6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 1.05058897e-046,
        2.95883255e-032],
       [2.35699783e+180, 1.93342618e-076, 6.53079593e-144,
        1.50008929e+248]])

In [99]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
np.linspace([2,8],10,endpoint=False,axis=0)

array([[2.  , 8.  ],
       [2.16, 8.04],
       [2.32, 8.08],
       [2.48, 8.12],
       [2.64, 8.16],
       [2.8 , 8.2 ],
       [2.96, 8.24],
       [3.12, 8.28],
       [3.28, 8.32],
       [3.44, 8.36],
       [3.6 , 8.4 ],
       [3.76, 8.44],
       [3.92, 8.48],
       [4.08, 8.52],
       [4.24, 8.56],
       [4.4 , 8.6 ],
       [4.56, 8.64],
       [4.72, 8.68],
       [4.88, 8.72],
       [5.04, 8.76],
       [5.2 , 8.8 ],
       [5.36, 8.84],
       [5.52, 8.88],
       [5.68, 8.92],
       [5.84, 8.96],
       [6.  , 9.  ],
       [6.16, 9.04],
       [6.32, 9.08],
       [6.48, 9.12],
       [6.64, 9.16],
       [6.8 , 9.2 ],
       [6.96, 9.24],
       [7.12, 9.28],
       [7.28, 9.32],
       [7.44, 9.36],
       [7.6 , 9.4 ],
       [7.76, 9.44],
       [7.92, 9.48],
       [8.08, 9.52],
       [8.24, 9.56],
       [8.4 , 9.6 ],
       [8.56, 9.64],
       [8.72, 9.68],
       [8.88, 9.72],
       [9.04, 9.76],
       [9.2 , 9.8 ],
       [9.36, 9.84],
       [9.52,

In [106]:
d=np.linspace(2,10,40)

In [107]:
d

array([ 2.        ,  2.20512821,  2.41025641,  2.61538462,  2.82051282,
        3.02564103,  3.23076923,  3.43589744,  3.64102564,  3.84615385,
        4.05128205,  4.25641026,  4.46153846,  4.66666667,  4.87179487,
        5.07692308,  5.28205128,  5.48717949,  5.69230769,  5.8974359 ,
        6.1025641 ,  6.30769231,  6.51282051,  6.71794872,  6.92307692,
        7.12820513,  7.33333333,  7.53846154,  7.74358974,  7.94871795,
        8.15384615,  8.35897436,  8.56410256,  8.76923077,  8.97435897,
        9.17948718,  9.38461538,  9.58974359,  9.79487179, 10.        ])

In [108]:
d.shape

(40,)

In [109]:
d.ndim

1

In [114]:
d.reshape(2,2,2,5)

array([[[[ 2.        ,  2.20512821,  2.41025641,  2.61538462,
           2.82051282],
         [ 3.02564103,  3.23076923,  3.43589744,  3.64102564,
           3.84615385]],

        [[ 4.05128205,  4.25641026,  4.46153846,  4.66666667,
           4.87179487],
         [ 5.07692308,  5.28205128,  5.48717949,  5.69230769,
           5.8974359 ]]],


       [[[ 6.1025641 ,  6.30769231,  6.51282051,  6.71794872,
           6.92307692],
         [ 7.12820513,  7.33333333,  7.53846154,  7.74358974,
           7.94871795]],

        [[ 8.15384615,  8.35897436,  8.56410256,  8.76923077,
           8.97435897],
         [ 9.17948718,  9.38461538,  9.58974359,  9.79487179,
          10.        ]]]])

In [115]:
np.random.rand(5)

array([0.22045888, 0.34363421, 0.48817323, 0.86725405, 0.08491802])

In [116]:
np.random.randn(5)

array([ 0.39678474, -0.19477875, -0.40363469,  1.29100898,  0.73129263])

In [117]:
arr=np.random.randint(5,20,(4,4))

In [118]:
arr

array([[15, 19, 14, 17],
       [10, 15, 14, 17],
       [16,  8,  5, 14],
       [14, 14, 19, 15]])

In [119]:
arr.shape

(4, 4)

In [120]:
arr.reshape(2,2,4)

array([[[15, 19, 14, 17],
        [10, 15, 14, 17]],

       [[16,  8,  5, 14],
        [14, 14, 19, 15]]])

In [125]:

arr.reshape(16,0)

ValueError: cannot reshape array of size 16 into shape (16,0)

In [126]:
arr=np.random.randint(5,50,(4,4))

In [127]:
arr

array([[17, 13, 13, 23],
       [22, 24, 47, 38],
       [31, 25, 46, 33],
       [ 6, 32, 32, 34]])

In [129]:
arr[2:,[0,1]]

array([[31, 25],
       [ 6, 32]])

In [131]:
arr[:2,[2,3]]

array([[13, 23],
       [47, 38]])

In [132]:
arr

array([[17, 13, 13, 23],
       [22, 24, 47, 38],
       [31, 25, 46, 33],
       [ 6, 32, 32, 34]])

In [133]:
arr>15

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [134]:
arr[arr>20]

array([23, 22, 24, 47, 38, 31, 25, 46, 33, 32, 32, 34])

In [135]:
arr1=np.random.randint(2,10,(3,3))

In [136]:
arr2=np.random.randint(2,10,(3,3))

In [137]:
arr1*arr2

array([[49, 40, 56],
       [54, 20, 27],
       [32, 18,  4]])

In [138]:
arr1@arr2

array([[107,  97, 115],
       [105, 101, 123],
       [100,  94, 122]])

In [139]:
arr1/arr2

array([[1.        , 0.625     , 0.875     ],
       [1.5       , 1.25      , 0.33333333],
       [2.        , 2.        , 1.        ]])

In [140]:
arr1+arr2

array([[14, 13, 15],
       [15,  9, 12],
       [12,  9,  4]])

In [150]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [151]:
b=np.zeros((3,4))

In [152]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [153]:
a+b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])