### 1. Write a NumPy program to print the NumPy version in your system.

In [1]:
import numpy as np
import array

In [7]:
print(np.__version__)

1.18.1


### 2 Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [8]:
l=[21,34,56,7890,]
np.array(l)

array([  21,   34,   56, 7890])

###  3 Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [9]:
np.random.randint(2,10,(3,3))

array([[7, 5, 9],
       [4, 2, 8],
       [6, 6, 7]])

In [10]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 4 Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [22]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
a[5]=11

In [27]:
a[6]=0

In [28]:
a

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

### 5Write a NumPy program to create an array with values ranging from 12 to 38

In [32]:
np.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

### 6  Write a NumPy program to reverse an array (first element becomes last).

In [40]:
a=np.arange(1,10)
a=a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

### 7 Write a NumPy program to convert an array to a float type.

In [43]:
a=np.array([1,2,3,4])

In [46]:
x=np.asfarray(a)

In [47]:
x

array([1., 2., 3., 4.])

### 8 Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [49]:
a=np.array([[1,1,1],[1,0,1],[1,1,1]])

In [50]:
a

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [51]:
a.ndim

2

In [52]:
x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
x[1:3,1:3]=0

In [54]:
x

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

### 9 Write a NumPy program to add a border (filled with 0's) around an existing array.



In [56]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.pad(a,pad_width=1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

### 10 Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [58]:
x=np.ones((8,8))

In [59]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [72]:
x[1::2,::2]=1
x[::2,1::2]=1

In [73]:
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### 11Write a NumPy program to convert a list and tuple into arrays.



In [77]:
a=[1,2,3,4]
b=(1,2,3,4)
print(np.asarray(a))
print(np.asarray(b))

[1 2 3 4]
[1 2 3 4]


### 12 Write a NumPy program to append values to the end of an array.



In [80]:
a=np.array([1,2,3])
x=np.append(a,[[4,5,6],[6,7,8]])
x

array([1, 2, 3, 4, 5, 6, 6, 7, 8])

### 13. Write a NumPy program to generate five random numbers from the normal distribution.

In [81]:
np.random.randn(5)

array([ 0.56091665, -0.79004183, -0.16418247, -0.0216642 , -0.1697374 ])

### 14 Write a NumPy program to generate six random integers between 10 and 30.



In [83]:
np.random.randint(10,30,6)

array([24, 28, 23, 19, 24, 10])

### 15 Write a NumPy program to create a 3x3x3 array with random values.

In [90]:
np.random.random((3,3,3))

array([[[0.1817858 , 0.94454063, 0.54114472],
        [0.36630504, 0.53019166, 0.5295231 ],
        [0.79699897, 0.64984647, 0.60470687]],

       [[0.59286891, 0.3991218 , 0.47354157],
        [0.44834831, 0.36657059, 0.20793258],
        [0.48291946, 0.59882117, 0.23376399]],

       [[0.11212537, 0.51130339, 0.59280265],
        [0.39140423, 0.14684034, 0.12996781],
        [0.81636236, 0.99207862, 0.30862902]]])

### 16 Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [93]:
a=np.random.random((5,5))
a

array([[0.07047675, 0.06278937, 0.99211814, 0.32453343, 0.39300548],
       [0.87640687, 0.10065996, 0.63685286, 0.08682357, 0.98284023],
       [0.69840517, 0.11624928, 0.88329038, 0.60444319, 0.77075043],
       [0.98028174, 0.17494732, 0.66389447, 0.85306952, 0.45218526],
       [0.04981002, 0.35473565, 0.30574266, 0.57762487, 0.05578179]])

In [95]:
a.max()

0.992118140963464

In [96]:
a.min()

0.04981002327721973

### 17 Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [97]:
x=np.random.random((10,4))

In [98]:
x

array([[0.69184137, 0.62892142, 0.05240396, 0.183086  ],
       [0.83132972, 0.84296975, 0.74159454, 0.22935901],
       [0.85790019, 0.91800399, 0.78409614, 0.47614133],
       [0.78612102, 0.1890287 , 0.46362775, 0.6856344 ],
       [0.66345871, 0.67862809, 0.83701361, 0.94030259],
       [0.50032685, 0.33059162, 0.65831429, 0.27000742],
       [0.71160763, 0.27234182, 0.30160568, 0.8998527 ],
       [0.31268383, 0.89548212, 0.07776534, 0.69447789],
       [0.92983302, 0.35649343, 0.16751469, 0.90023729],
       [0.56268919, 0.57060547, 0.27433655, 0.67922509]])

In [100]:
x.shape

(10, 4)

In [102]:
a=x[:5,:5]

In [103]:
a

array([[0.69184137, 0.62892142, 0.05240396, 0.183086  ],
       [0.83132972, 0.84296975, 0.74159454, 0.22935901],
       [0.85790019, 0.91800399, 0.78409614, 0.47614133],
       [0.78612102, 0.1890287 , 0.46362775, 0.6856344 ],
       [0.66345871, 0.67862809, 0.83701361, 0.94030259]])

### 18 Write a NumPy program to shuffle numbers between 0 and 10 (inclusive)

In [111]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.random.shuffle(x)

In [113]:
x

array([8, 9, 4, 6, 1, 7, 5, 3, 0, 2])

### 19 Write a NumPy program to normalize a 3x3 random matrix.

In [115]:
a=np.random.random((3,3))
a

array([[0.45793995, 0.81056329, 0.31209188],
       [0.86183538, 0.8702371 , 0.48189178],
       [0.41097953, 0.50541367, 0.6939691 ]])

In [119]:
amax,amin=a.max(),a.min()
a=(a-amin)/(amax-amin)

In [120]:
a

array([[0.26130847, 0.89308552, 0.        ],
       [0.98494708, 1.        , 0.30422172],
       [0.1771719 , 0.34636467, 0.68418972]])

### 20 Write a NumPy program to create a random vector of size 10 and sort it.

In [121]:
a=np.random.random((10))

In [122]:
a

array([0.43913089, 0.71694534, 0.41127901, 0.62886675, 0.24123822,
       0.06773018, 0.19838861, 0.905066  , 0.70595015, 0.64239589])

In [124]:
a.sort()

In [125]:
a

array([0.06773018, 0.19838861, 0.24123822, 0.41127901, 0.43913089,
       0.62886675, 0.64239589, 0.70595015, 0.71694534, 0.905066  ])